name: Smoke Test CI
run-name: CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  workflow_dispatch:
  merge_group:
  push:
  schedule:
    #      Run at the end of every day
    - cron: "0 0 * * *"

# Cancel in-progress jobs except for integration branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'integration/')}}


jobs:
  smoke_test:

    strategy:
      matrix:
        test-script: [ ./smoke-test.bash, ./smoke-test-l3.bash, ./smoke-test-nitro-simple.bash, ./smoke-test-full-node.bash ]

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      # Explicitly building the docker images because it's not clear how we can
      # use the github action (gha) cache if we let docker compose build the images.
      - uses: docker/build-push-action@v5
        with:
          context: ./rollupcreator
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Use default branch from test-node.bash
          build-args: |
            NITRO_CONTRACTS_BRANCH=develop

      - uses: docker/build-push-action@v5
        with:
          context: ./scripts
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v5
        with:
          context: ./tokenbridge
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Use default branch from test-node.bash
          build-args: |
            TOKEN_BRIDGE_BRANCH=v1.2.2

      - name: Smoke Test with Latest Espresso Image
        run: |
          ${{ matrix.test-script }}
        timeout-minutes: 30
